service: myslack-bot

provider:
  name: aws
  runtime: python3.8

# ステージを指定。開発と本番環境を切り分け
  stage: dev
# デプロイするリージョンを指定
  region: ap-northeast-1
  environment:
    # .envから値を取得してセット
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
  dockerizePip: true


functions:
  # 関数名を指定
  slackapp:
    # handler関数を指定
    handler: wsgi.handler
    # Lambdaのイベントトリガーを設定
    events:
      # トリガーとしてAPIGatewayを構築
      - http: ANY /
      - http: 'ANY {proxy+}'
